version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
      PGDATA: "/data/postgres"
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - database_network

  pgadmin:
    image: "dpage/pgadmin4:6.8"
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    ports:
      - "${PGADMIN_PORT}:8765"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - database_network
      - https

networks:
  database_network:
    name: ${DATABASE_NETWORK}
    external: true
  https:
    name: ${HTTPS_NETWORK}
    external: true      

volumes:
  pgadmin_data:
  postgres_data:
