version: "3"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
      PGDATA: "/data/postgres"
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - database_network
 
  pgadmin:
    image: "dpage/pgadmin4:5.7"
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
      VIRTUAL_HOST: ${PGADMIN_SSL_DOMAIN}
      VIRTUAL_PORT: ${PGADMIN_PORT}
      LETSENCRYPT_HOST: ${PGADMIN_SSL_DOMAIN}
    ports:
      - "${PGADMIN_PORT}:8765"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - database_network
      - https

networks:
  database_network:
    external:
      name: ${DATABASE_NETWORK}
  https:
    external:
      name: ${HTTPS_NETWORK}

volumes:
  pgadmin_data:
  postgres_data:
