version: "3"

services:
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
      PGDATA: "/data/postgres"
      VIRTUAL_HOST: ${POSTGRES_SSL_DOMAIN}
      VIRTUAL_PORT: ${POSTGRES_PORT}
      LETSENCRYPT_HOST: ${POSTGRES_SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${DEFAULT_EMAIL}
    volumes:
      - "./postgres-data:/data/postgres"
    ports:
      - "${POSTGRES_PORT}:5432"
 
  pgadmin:
    image: "dpage/pgadmin4"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
      VIRTUAL_HOST: ${PGADMIN_SSL_DOMAIN}
      VIRTUAL_PORT: ${PGADMIN_PORT}
      LETSENCRYPT_HOST: ${PGADMIN_SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${DEFAULT_EMAIL}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - "./pgadmin-data:/root/.pgadmin"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: ${NGINX_PROXY_NETWORK}
