version: "3"

services:
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB}
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
      PGDATA: "/data/postgres"
    volumes:
      - "./postgres-data:/data/postgres"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres
 
  pgadmin:
    image: "dpage/pgadmin4"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      VIRTUAL_HOST: ${SSL_DOMAIN}
      VIRTUAL_PORT: ${PGADMIN_PORT}
      LETSENCRYPT_HOST: ${SSL_DOMAIN}
      LETSENCRYPT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - "./pgadmin-data:/root/.pgadmin"
    links:
      - "database:pgsql-server"
    networks:
      - postgres
      - proxy

networks:
  postgres:
    driver: bridge
  proxy:
    external:
      name: ${NGINX_PROXY_NETWORK}
